version: "3"

volumes:
  node_data: {}

services:
    client:
        image: node:12.10.0
        container_name: reactjs
        expose:
            - 3000
        restart: on-failure
        deploy:
          restart_policy:
            condition: on-failure
        ports:
            - 3000:3000
        volumes:
            - "./:/home/app/"
        command: sh -c "cd /home/app && npm install --save && npm start"